apiVersion: v1
kind: Service
metadata:
  name: shopping-cart-service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 3002
    protocol: TCP
  selector:
    app: shopping-cart